<div class="card p-3 m-2 w-75 mx-auto">
    <div class="jumbotron text-center">
        <h2>A tartalom megtekintéséhez bejelentkezés szükséges!</h2>
    </div>
</div>

<form action="/login" class="w-75 mx-auto" method="post">
    <label class="w-100">
        E-mail:
        <input class="form-control" type="email" name="email">
    </label>
    <labe class="w-100">
        Password
        <input class="form-control" type="password" name="password">
    </labe>
    <button class="btn btn-primary form-control my-3" type="submit">Login</button>
</form>

<form action="/register" class="w-75 mx-auto" method="post">
    <label class="w-100">
        E-mail:
        <input class="form-control" type="email" name="email">
    </label>
    <labe class="w-100">
        Password
        <input class="form-control" type="password" name="password">
    </labe>
    <button class="btn btn-success form-control my-3" type="submit">Registration</button>
</form>
