<div class="card p-3 m-2 w-75 mx-auto">
    <div class="jumbotron text-center">
        <h2>A tartalom megtekintéséhez bejelentkezés szükséges!</h2>
    </div>
</div>

<?php if ($params['info'] === 'invalidCredentials'): ?>
    <div class="alert alert-danger w-75 mx-auto">
        Invalid login values!
    </div>
<?php endif;?>

<?php if ($params['info'] === 'registrationSuccessful'): ?>
    <div class="alert alert-success w-75 mx-auto">
        Successful registration!
    </div>
<?php endif;?>

<?php if ($params['isRegistration']): ?>
    <form action="/register" class="w-75 mx-auto" method="post">
        <label class="w-100">
            E-mail:
            <input class="form-control" type="email" name="email">
        </label>
        <labe class="w-100">
            Password
            <input class="form-control" type="password" name="password">
        </labe>
        <button class="btn btn-success form-control my-3" type="submit">Registration</button>
    </form>
    Van már felhasználói fiókod?
    <a href="<?= $params['url'] ?>">Bejelentkezés</a>
<?php else :?>
    <form action="/login" class="w-75 mx-auto" method="post">
    <label class="w-100">
        E-mail:
        <input class="form-control" type="email" name="email">
    </label>
    <labe class="w-100">
        Password
        <input class="form-control" type="password" name="password">
    </labe>
    <button class="btn btn-primary form-control my-3" type="submit">Login</button>
    </form>
    Nincs még felhasználói fiókod?
    <a href="<?= $params['url'] ?>&isRegistration=1">Regisztráció</a>
<?php endif;?>